### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by grahamkirby**
Update README, to fix broken links.

### CODE REVIEW

**Comment by masih** [comment]
Re build failure I think [this](https://github.com/stacs-srg/shabdiz/blob/master/core/src/main/java/uk/ac/standrews/cs/shabdiz/host/exec/MavenDependencyResolver.java#L46) needs to point at `https`.

**Comment by grahamkirby** [comment]
Sounds sensible - will you change it? Not sure if I can.

**Comment by masih** [comment]
😱 the permissions were not right, sorry, you are now admin of this repo.

**Review by masih — APPROVED** [review]
@grahamkirby many thanks for updating the README, happy to merge if there are no further updates to this PR.

**Comment by grahamkirby** [comment]
No worries, thanks.
G

**Pull request merged**
